// <auto-generated />
using System;
using AmalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmalAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("AmalApi.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BloodGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNIC")
                        .HasColumnType("TEXT");

                    b.Property<double>("CityCode")
                        .HasColumnType("REAL");

                    b.Property<double>("CountryCode")
                        .HasColumnType("REAL");

                    b.Property<string>("DMLInsertBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DMLInsertDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOD")
                        .HasColumnType("TEXT");

                    b.Property<double>("EmergencyContactMobNo")
                        .HasColumnType("REAL");

                    b.Property<double>("EmergencyContactPerson")
                        .HasColumnType("REAL");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<double>("MobileNumber")
                        .HasColumnType("REAL");

                    b.Property<int>("MrNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Passport")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientMiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
